version: '3'
services:
  mission1:
    image: jupyter/base-notebook
    container_name: jupyter-notebook
    ports:
      - "8888:8888"
    volumes:
      - ./local_jupyter:/home/jovyan/work/
    command: start-notebook.sh --NotebookApp.token=''